### ISSUE TITLE
Package thumbnail generator into transcoder Docker image

### ISSUE THREAD

**Issue by andybeletsky** [OdyseeTeam/transcoder#28]
For generating thumbnails after transcoding, [video-thumbnail-generator](https://github.com/andybeletsky/video-thumbnail-generator) needs to be baked into Docker image in a way that would allow convenient invocation by transcoder.

**Comment by b-rad-c** [comment]
I pushed my updates [here](https://github.com/b-rad-c/transcoder/tree/add-thumbnail-gen), the generator is available at this path: `/app/video-thumbnail-generator/generator` 

To test run these commands inside the container
<pre>
cd /app/video-thumbnail-generator
wget http://download.opencontent.netflix.com.s3.amazonaws.com/SolLevante/working_assets/SolLevante_Animatics_ver1_H264.mov
./generator SolLevante_Animatics_ver1_H264.mov 20 150 150 4 SolLevante-thumbs.png
</pre>

From outside the container run this to copy the output locally to inspect:
<pre>docker cp [container_id]:/app/video-thumbnail-generator/SolLevante-thumbs.png SolLevante-thumbs.png</pre>
